# Generated by Django 4.0 on 2023-12-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
